### PR TITLE
Updates repository tooling and adds CI to run tests

### PR DESCRIPTION
**Pull request by austingebauer**
This PR updates the tooling for the repository. The changes originate from the Vault plugin scaffold. This should make the plugin's tooling and automated testing more consistent with other Vault plugins.

### CODE REVIEW

**Review by robmonte — COMMENTED** [review]
The changes with/from gofumpt look good. Not sure how to validate or comment on GitHub Actions additions like this though.

Also it looks like this repo doesn't require approvals for merging into main.

**Comment by austingebauer** [comment]
@robmonte - Thanks! I added branch protection for main. The GitHub actions are from our Vault plugin scaffold, so they're already reviewed / being used by the team in new plugins.

**Comment by austingebauer** [comment]
Also, this plugin wasn't running tests in CI before, so it's definitely an improvement :)

**Review by robmonte — APPROVED** [review]
Looks good to me

**Pull request merged**
