### PR TITLE
Add password policy support

### PR DESCRIPTION
**Pull request by pcman312**
# Overview
Allows users to specify a password policy to generate passwords from rather than hard coded to base62.
* If no policy is specified, it defaults back to base62.
* The `length` field has been deprecated. If both `length` and `password_policy` are specified, the configuration will error on save.
* Changed some of the unit tests in `path_config_test.go` to table tests.

<details>
<summary>Test output - I ran this a bunch of times to check for flakiness</summary>

```
$ make test
==> Checking that code complies with gofmt requirements...
go generate 
CGO_ENABLED=0 VAULT_TOKEN= VAULT_ACC= go test -v -tags='vault-plugin-secrets-openldap' $(go list ./... | grep -v /vendor/ | grep -v teamcity)  -count=1 -timeout=20m -parallel=4
=== RUN   TestConfig_Create
=== RUN   TestConfig_Create/happy_path_with_defaults
=== RUN   TestConfig_Create/minimum_config
=== RUN   TestConfig_Create/missing_binddn
=== RUN   TestConfig_Create/password_policy
=== RUN   TestConfig_Create/password_length
=== RUN   TestConfig_Create/both_password_policy_and_password_length
--- PASS: TestConfig_Create (0.00s)
    --- PASS: TestConfig_Create/happy_path_with_defaults (0.00s)
    --- PASS: TestConfig_Create/minimum_config (0.00s)
    --- PASS: TestConfig_Create/missing_binddn (0.00s)
    --- PASS: TestConfig_Create/password_policy (0.00s)
    --- PASS: TestConfig_Create/password_length (0.00s)
    --- PASS: TestConfig_Create/both_password_policy_and_password_length (0.00s)
=== RUN   TestConfig_Update
=== RUN   TestConfig_Update/happy_path
=== RUN   TestConfig_Update/missing_bindpass
--- PASS: TestConfig_Update (0.00s)
    --- PASS: TestConfig_Update/happy_path (0.00s)
    --- PASS: TestConfig_Update/missing_bindpass (0.00s)
=== RUN   TestConfig_Delete
=== RUN   TestConfig_Delete/happy_path
--- PASS: TestConfig_Delete (0.00s)
    --- PASS: TestConfig_Delete/happy_path (0.00s)
=== RUN   TestCreds
=== RUN   TestCreds/happy_path_with_creds
=== RUN   TestCreds/cred_doesn't_exist
--- PASS: TestCreds (0.00s)
    --- PASS: TestCreds/happy_path_with_creds (0.00s)
    --- PASS: TestCreds/cred_doesn't_exist (0.00s)
=== RUN   TestRoles
=== RUN   TestRoles/happy_path_with_roles
=== RUN   TestRoles/happy_path_with_roles#01
=== RUN   TestRoles/missing_dn
=== RUN   TestRoles/missing_username
=== RUN   TestRoles/missing_rotation_period
=== RUN   TestRoles/rotation_period_lower_than_5s
=== RUN   TestRoles/user_doesn't_exist_(ldap_error)
=== RUN   TestRoles/role_doesn't_exist
--- PASS: TestRoles (0.00s)
    --- PASS: TestRoles/happy_path_with_roles (0.00s)
    --- PASS: TestRoles/happy_path_with_roles#01 (0.00s)
    --- PASS: TestRoles/missing_dn (0.00s)
    --- PASS: TestRoles/missing_username (0.00s)
    --- PASS: TestRoles/missing_rotation_period (0.00s)
    --- PASS: TestRoles/rotation_period_lower_than_5s (0.00s)
    --- PASS: TestRoles/user_doesn't_exist_(ldap_error) (0.00s)
    --- PASS: TestRoles/role_doesn't_exist (0.00s)
=== RUN   TestListRoles
=== RUN   TestListRoles/list_roles
--- PASS: TestListRoles (0.00s)
    --- PASS: TestListRoles/list_roles (0.00s)
=== RUN   TestManaulRotate
=== RUN   TestManaulRotate/rotate_root
=== RUN   TestManaulRotate/rotate_root_that_doesn't_exist
=== RUN   TestManaulRotate/rotate_role
=== RUN   TestManaulRotate/rotate_role_that_doesn't_exist
--- PASS: TestManaulRotate (0.00s)
    --- PASS: TestManaulRotate/rotate_root (0.00s)
    --- PASS: TestManaulRotate/rotate_root_that_doesn't_exist (0.00s)
    --- PASS: TestManaulRotate/rotate_role (0.00s)
    --- PASS: TestManaulRotate/rotate_role_that_doesn't_exist (0.00s)
=== RUN   TestAutoRotate
=== RUN   TestAutoRotate/auto_rotate_role
--- PASS: TestAutoRotate (6.00s)
    --- PASS: TestAutoRotate/auto_rotate_role (6.00s)
PASS
ok  	github.com/hashicorp/vault-plugin-secrets-openldap	6.494s
=== RUN   TestSearch
--- PASS: TestSearch (0.00s)
=== RUN   TestUpdateEntry
--- PASS: TestUpdateEntry (0.00s)
=== RUN   TestUpdatePasswordOpenLDAP
--- PASS: TestUpdatePasswordOpenLDAP (0.00s)
=== RUN   TestUpdatePasswordRACF
--- PASS: TestUpdatePasswordRACF (0.00s)
=== RUN   TestUpdateRootPassword
--- PASS: TestUpdateRootPassword (0.00s)
=== RUN   TestIfEntryCreationIsRacy
--- PASS: TestIfEntryCreationIsRacy (1.01s)
=== RUN   TestFieldRegistryEqualityComparisonsWork
--- PASS: TestFieldRegistryEqualityComparisonsWork (0.00s)
=== RUN   TestFieldRegistryParsesFieldsByString
--- PASS: TestFieldRegistryParsesFieldsByString (0.00s)
PASS
ok  	github.com/hashicorp/vault-plugin-secrets-openldap/client	2.733s
?   	github.com/hashicorp/vault-plugin-secrets-openldap/client/tools	[no test files]
?   	github.com/hashicorp/vault-plugin-secrets-openldap/cmd/vault-plugin-secrets-openldap	[no test files]
?   	github.com/hashicorp/vault-plugin-secrets-openldap/ldapifc	[no test files]
```
</details>

<details>
<summary>Manually running it</summary>

```shell
##################################################################
# No length nor password policy specified doesn't show either field

$ vault write openldap/config \
  binddn="cn=admin,dc=hashicorp,dc=com" \
  bindpass="admin" url="ldap://127.0.0.1"
Success! Data written to: openldap/config

$ vault read openldap/config
Key                       Value
---                       -----
anonymous_group_search    false
binddn                    cn=admin,dc=hashicorp,dc=com
case_sensitive_names      false
certificate               n/a
deny_null_bind            true
discoverdn                false
groupattr                 cn
groupdn                   n/a
groupfilter               (|(memberUid={{.Username}})(member={{.UserDN}})(uniqueMember={{.UserDN}}))
insecure_tls              false
starttls                  false
tls_max_version           tls12
tls_min_version           tls12
upndomain                 n/a
url                       ldap://127.0.0.1
use_token_groups          false
userattr                  cn
userdn                    n/a

#################################################
# Backwards compatibility - length field is saved

$ vault write openldap/config \
  binddn="cn=admin,dc=hashicorp,dc=com" \
  bindpass="admin" url="ldap://127.0.0.1" \
  length=20
Success! Data written to: openldap/config

$ vault read openldap/config
Key                       Value
---                       -----
anonymous_group_search    false
binddn                    cn=admin,dc=hashicorp,dc=com
case_sensitive_names      false
certificate               n/a
deny_null_bind            true
discoverdn                false
groupattr                 cn
groupdn                   n/a
groupfilter               (|(memberUid={{.Username}})(member={{.UserDN}})(uniqueMember={{.UserDN}}))
insecure_tls              false
length                    20
starttls                  false
tls_max_version           tls12
tls_min_version           tls12
upndomain                 n/a
url                       ldap://127.0.0.1
use_token_groups          false
userattr                  cn
userdn                    n/a

#######################
# Password policy usage

$ cat openldap_policy.hcl
length = 20
rule "charset" {
  charset = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
}

$ vault write sys/policies/password/openldap_policy policy=@openldap_policy.hcl
Success! Data written to: sys/policies/password/openldap_policy

$ vault write openldap/config \
  binddn="cn=admin,dc=hashicorp,dc=com" \
  bindpass="admin" \
  url="ldap://127.0.0.1" \
  password_policy=openldap_policy
Success! Data written to: openldap/config

$ vault read openldap/config
Key                       Value
---                       -----
anonymous_group_search    false
binddn                    cn=admin,dc=hashicorp,dc=com
case_sensitive_names      false
certificate               n/a
deny_null_bind            true
discoverdn                false
groupattr                 cn
groupdn                   n/a
groupfilter               (|(memberUid={{.Username}})(member={{.UserDN}})(uniqueMember={{.UserDN}}))
insecure_tls              false
password_policy           openldap_policy
starttls                  false
tls_max_version           tls12
tls_min_version           tls12
upndomain                 n/a
url                       ldap://127.0.0.1
use_token_groups          false
userattr                  cn
userdn                    n/a

$ vault write openldap/static-role/hashicorp \
  username='hashicorp' \
  dn='uid=hashicorp,ou=users,dc=hashicorp,dc=com' \
  rotation_period="5s"
Success! Data written to: openldap/static-role/hashicorp

$ vault read openldap/static-cred/hashicorp
Key                    Value
---                    -----
dn                     uid=hashicorp,ou=users,dc=hashicorp,dc=com
last_vault_rotation    2020-05-20T13:35:53.490445-06:00
password               B3eS3uXYueD2i0QWSOEJ
rotation_period        5s
ttl                    4s
username               hashicorp
```
</details>

## Note about PR size
The **vast** majority of this PR is vendoring:
`183 files changed, 36098 insertions(+), 14737 deletions(-)`
vs non-vendor:
`8 files changed, 365 insertions(+), 203 deletions(-)`

# Design of Change
Uses the new [Password Policies](https://github.com/hashicorp/vault/pull/8637) available in Vault

# Related Issues/Pull Requests
https://github.com/hashicorp/vault/pull/8637

# Contributor Checklist
- [ ] Add relevant docs to upstream Vault repository, or sufficient reasoning why docs won’t be added yet
[My Docs PR Link](link) (TBD - separate PR)
- [x] Add output for any tests not ran in CI to the PR description (eg, acceptance tests)
  - See above
- [x] Backwards compatible

### CODE REVIEW

**Comment by jasonodonnell** [comment]
> The length field has been deprecated. If both length and password_policy are specified, the configuration will error on save.

This seems confusing.  Is `length` deprecated or not?  If it truly is gone, what's the migration path for existing users?

**Comment by pcman312** [comment]
`length` hasn't been removed so we don't break existing users. It has been deprecated to encourage new users to not use it. It is still a valid field to specify, which is why I included that note.

**Comment by jasonodonnell** [comment]
Perfect, thanks!  We'll need to add a note to the documentation about this.

**Comment by pcman312** [comment]
I'll make sure there's a note about it!

**Pull request merged**
